version: '3.2'

services:
  trrbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trrbot-ts-bolt
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./trrbot-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
